version: 2

jobs:
  build-bash:
    macos:
      xcode: 9.2.0
    steps:
      - checkout
      - run:
          name: Bash Install
          command: |
            echo $0
            source install/all.sh

  build-zsh:
    macos:
      xcode: 9.2.0
    steps:
      - checkout
      - run:
          name: ZSH Install
          command: |
            echo $0
            SHELL=/usr/local/bin/zsh
            ./install/all.sh

workflows:
  version: 2
  build:
    jobs:
      - build-bash
      - build-zsh
