version: 2

references:

  ## Install Steps

  install_golang: &install_golang
    run:
      name: Install Golang
      command: .circleci/install/golang.sh

  install_dots: &install_dots
    run:
      name: Installing Dots
      command: go get -u github.com/drn/dots

  ## Cache

  cache_brew: &cache_brew
    save_cache:
      name: Cache Homebrew
      key: v1-brew-{{ .Branch }}-{{ .Revision }}
      paths:
        - /usr/local/Homebrew

  restore_brew: &restore_brew
    restore_cache:
      name: Restore Homebrew
      keys:
        - v1-brew-{{ .Branch }}-{{ .Revision }}
        - v1-brew-{{ .Branch }}
        - v1-brew

  cache_go: &cache_go
    save_cache:
      name: Cache $GOPATH
      key: v1-go-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/go

  restore_go: &restore_go
    restore_cache:
      name: Restore $GOPATH
      keys:
        - v1-go-{{ .Branch }}-{{ .Revision }}

  ## General

  setup_path: &setup_path
    run:
      name: Setting Up $PATH
      command: |
        echo 'export PATH=$HOME/go/bin:$PATH' >> $BASH_ENV

  ## Step Wrappers

  dots_steps: &dots_steps
    steps:
      - checkout
      - *restore_brew
      - *restore_go
      - *setup_path
      - run:
          name: Running Command
          command: eval $COMMAND

jobs:
  build:
    macos:
      xcode: 9.2.0
    steps:
      - checkout
      - *restore_brew
      - run:
          name: Brew Update
          command: |
            rm -rf /usr/local/Homebrew/Library/Taps
            brew update
      - *cache_brew
      - *install_golang
      - *install_dots
      - *cache_go
      - run:
          name: Running Dots Root
          command: dots

  dots-install:
    macos:
      xcode: 9.2.0
    environment:
      COMMAND: 'dots install all'
    <<: *dots_steps

  dots-update:
    macos:
      xcode: 9.2.0
    environment:
      COMMAND: 'dots update'
    <<: *dots_steps

  dots-cleanup:
    macos:
      xcode: 9.2.0
    environment:
      COMMAND: 'dots cleanup'
    <<: *dots_steps

  ruby-lint:
    machine: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Gemfile Cache
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems
      - run:
          name: Install Gemfile Dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Save Gemfile Cache
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Ruby Lint
          command: bundle exec rubocop

  go-lint:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Golint
          command: go get -u golang.org/x/lint/golint
      - run:
          name: Go Lint
          command: golint -set_exit_status ./...

workflows:
  version: 2
  build:
    jobs:
      - build
      - ruby-lint
      - go-lint
      - dots-install:
          requires:
            - build
      - dots-update:
          requires:
            - build
      - dots-cleanup:
          requires:
            - build
