version: 2

jobs:
  build-bash:
    macos:
      xcode: 9.2.0
    steps:
      - checkout
      - run:
          name: Bash Install
          command: |
            echo $0
            echo 'TODO'

  build-zsh:
    macos:
      xcode: 9.2.0
    steps:
      - checkout
      - run:
          name: ZSH Install
          command: |
            echo $0
            SHELL=/usr/local/bin/zsh
            echo 'TODO'

  ruby-lint:
    machine: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Gemfile Cache
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems
      - run:
          name: Install Gemfile Dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Save Gemfile Cache
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Ruby Lint
          command: bundle exec rubocop

  go-lint:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Golint
          command: go get -u golang.org/x/lint/golint
      - run:
          name: Go Lint
          command: golint -set_exit_status ./...

workflows:
  version: 2
  build:
    jobs:
      - build-bash
      - build-zsh
      - ruby-lint
      - go-lint
